language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t borislad/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true borislad/docker-react npm run test 